// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://limgkhmpzdgdthyxoemm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpbWdraG1wemRnZHRoeXhvZW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjM2MDcsImV4cCI6MjA2NjU5OTYwN30.Qtfp4cDt1IiqEZbA1vq4i8q7AV_VtR_bqv9j2SpSLls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);